call code --install-extension akamud.vscode-theme-onedark 
call code --install-extension bierner.markdown-preview-github-styles 
call code --install-extension darkriszty.markdown-table-prettify 
call code --install-extension DavidAnson.vscode-markdownlint 
call code --install-extension eamodio.gitlens 
call code --install-extension ionutvmi.reg 
call code --install-extension mauve.terraform 
call code --install-extension ms-python.python 
call code --install-extension ms-vscode.atom-keybindings 
call code --install-extension ms-vscode.csharp 
call code --install-extension ms-vscode.PowerShell 
call code --install-extension rafaelmaiolla.remote-vscode 
call code --install-extension richardmarks.vscode-perfect-dark-color-theme 
call code --install-extension shd101wyy.markdown-preview-enhanced 
call code --install-extension sohamkamani.code-eol 
call code --install-extension yzane.markdown-pdf 
call code --install-extension yzhang.markdown-all-in-one 
