export PATH="/usr/local/sbin:$PATH"

alias brewup='brew update; brew upgrade; brew prune; brew cleanup; brew doctor'

# use antigen
source "$HOME/.antigen/antigen.zsh"

# Load oh-my-zsh's library
antigen use oh-my-zsh

POWERLEVEL9K_INSTALLATION_PATH=$ANTIGEN_BUNDLES/bhilburn/powerlevel9k
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir rbenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs history time)
antigen theme bhilburn/powerlevel9k powerlevel9k 

antigen bundle git
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle command-not-found
antigen bundle common-aliases
antigen bundle please
antigen bundle brew
antigen bundle osx

antigen apply
